array manipulation 1
allen-huang9/c1020-code-solutions pull request #38
Opened 2020-10-17 00:10 UTC by allen-huang9

![image](https://user-images.githubusercontent.com/8008839/96323560-724b0500-0fd2-11eb-8015-d518735581e7.png)
![image](https://user-images.githubusercontent.com/8008839/96323568-7c6d0380-0fd2-11eb-97a5-a1791f921167.png)

2020-10-19 20:09 UTC, codingcodymiller requested changes

2020-10-19 20:09 UTC, codingcodymiller commented on array-manipulation-1/src/last.js
> +  if (array.length > 0) {
If the array length is 0, wouldn't the value of the `array[array.length - 1]` be `undefined` anyway?

2020-11-05 18:43 UTC, uzair-ashraf requested changes

2020-11-05 18:43 UTC, uzair-ashraf commented on array-manipulation-1/src/head.js
> +}
If the array length was not greater than zero, it would return undefined anyway.

2020-11-05 19:09 UTC, uzair-ashraf approved these changes

2020-11-05 19:11 UTC, merged